spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=utf-8&useSSL=false&&serverTimezone=UTC
    username: root
    password: qiu123456hui
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always





#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置

mybatis:
  type-aliases-package: com.example.bean
  configuration:
    #开启mybatis的驼峰命名，否则数据库字段映射到实体时，驼峰字段会为空
    map-underscore-to-camel-case: true